// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Domain.Entities.Company", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadOffice")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalSeat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Legalform")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SogcDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Uid");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("Domain.Entities.CompanyAdresses", b =>
                {
                    b.Property<string>("CompanyUid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyUid");

                    b.ToTable("CompanyAdresses");
                });

            modelBuilder.Entity("Domain.Entities.CompanyAdresses", b =>
                {
                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithOne("Adresses")
                        .HasForeignKey("Domain.Entities.CompanyAdresses", "CompanyUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.Company", b =>
                {
                    b.Navigation("Adresses");
                });
#pragma warning restore 612, 618
        }
    }
}
